# Generated by Django 4.2.1 on 2026-06-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='copied_file_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='extracted_text_path',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
