# Generated by Django 4.2.1 on 2026-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0002_document_copied_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contracting_parties',
            field=models.TextField(blank=True, null=True),
        ),
    ]
