# Generated by Django 4.2.1 on 2026-07-02 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_document_contracting_parties'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='contract_duration',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
